import type { Metadata } from "next";

import "./globals.css";
import { Header } from "@/components/Header/Header";

import localFont from "next/font/local";

export const myFont = localFont({
  src: [
    {
      path: "./fonts/FixelDisplay-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/FixelDisplay-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-myfont",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.variable}  antialiased container`}>
        <Header />

        <main>{children}</main>

        <footer>
          <p>
            Created <time dateTime="2025">2025</time>
          </p>
        </footer>
      </body>
    </html>
  );
}
